## Linear Algebra Problems

### Basic Matrix Operations

1. Matrix Operation Perform the following operations on the given matrices: A=[[2 -1], [​0 3​]] B=[[1 ​ 2], [-3 4​]] a. A+B b. AB c. 3A−2B

In [3]:
from matplotlib.pylab import beta
import numpy as np
import numpy.linalg as la

Define two matrices A and B

In [4]:
A = np.array([[2, -1], [0, 3]])
B = np.array([[1, 2], [3, 4]])
print("Matrix A:\n", A)
print("\n Matrix B:\n", B)

Matrix A:
 [[ 2 -1]
 [ 0  3]]

 Matrix B:
 [[1 2]
 [3 4]]


##### Matrix Addition

In [5]:
C = A + B
print("\n Matrix Addition:\n A + B =", C)


 Matrix Addition:
 A + B = [[3 1]
 [3 7]]


#### Matrix Multiplicaiton

In [6]:
D = np.dot(A, B)
# We can also use D=A@B and A.dot(B)
print("\n Matrix Multiplication:\n A * B =", D)


 Matrix Multiplication:
 A * B = [[-1  0]
 [ 9 12]]


#### Matrix Subtraction

In [7]:
E = 3 * A - 2 * B
print("\n Matrix Subtraction:\n 3A - 2B =", E)


 Matrix Subtraction:
 3A - 2B = [[ 4 -7]
 [-6  1]]


### Determinant and Inverse

2. Find the determinant of A. Determine whether A is invertible. If yes, calculate A^−1.

#### Determinant of matrix A

In [12]:
print("Matrix A=\n", A)
det_A = la.det(A)
print("\n Determinant of A:", det_A)

Matrix A=
 [[ 2 -1]
 [ 0  3]]

 Determinant of A: 6.0


#### Inverse of A

In [13]:
if det_A != 0:
    inv_A = la.inv(A)
    print("\n Inverse of A:\n", inv_A)


 Inverse of A:
 [[0.5        0.16666667]
 [0.         0.33333333]]


### Eigen Values and Eigen Vectors

3. Compute the eigenvalues and eigenvectors of the matrix:
C=[[4    1], [​−2       1]​]


In [10]:
C = np.array([[4, 1], [-2, 1]])
eigenvalues, eigenvectors = la.eig(C)

# Print the results
print("\n Matrix C:")
print(C)
print("\n Eigenvalue (first): ")
print(eigenvalues[0])
print("\n Corresponding Eigenvector:")
print(eigenvectors[:, 0])



 Matrix C:
[[ 4  1]
 [-2  1]]

 Eigenvalue (first): 
3.0

 Corresponding Eigenvector:
[ 0.70710678 -0.70710678]


4. You are given a dataset of cars with the following features:Number of cylinders (x1​)Engine size in liters (x2​)Horsepower (x3)
car 1: x1: 4 x2:  1.5 x3: 100 and price: 20

    car 2: x1: 6 x2:  2.0 x3: 150 and price: 30

    Then, find the price of a car 3 with features
    x1: 8 x2:  3.0 x3: 200 price:?

In [11]:
X = np.array([
    [4, 1.5, 100],   
     [6, 2.0, 150]   
])

Y = np.array([20, 30])


beta = np.linalg.pinv(X.T @ X) @ X.T @ Y

# beta = np.linalg.pinv(X) @ Y

# beta = np.linalg.lstsq(X, Y,rcond=None)[0] #<- returns a tuple with first elements solution , then other stuffs too
print("β =", beta)

car3= np.array([
    [8, 3.0, 200]
])

price_car3 = car3 @ beta

#dot product returns a matrix so [0]
print(f" price of car 3 : {price_car3[0]}")

β = [ 7.98722045e-03 -4.12114787e-13  1.99680511e-01]
 price of car 3 : 39.99999999999998
